# This workflow will build and push a new container image to Amazon ECR
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of `ECR_REPOSITORY` in the workflow below with your repository's name.
#    Replace the value of `aws-region` in the workflow below with your repository's region.
#    ***Variables***
#    ECR_REPOSITORY: ECR repository name
#    working-directory: Directory in git repository which has tag/version file
#    IMAGE_TAG=$( cat path to file of tag/version )   
#sdasd
#
#
on:
  push:
    branches: [ master ]
  #pull_request:
  #  branches: [ master ]

name: Python Project `my-app` CI on ECR

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
    - id: release
      uses: rohailkhaniazi/release-action@master
      with:
        bump_version_scheme: minor
        #tag_prefix: ""
        #tag_name: "0.0"
    #- name: Checkout
    #  uses: actions/checkout@v2
    #- name: Configure AWS credentials
      #uses: aws-actions/configure-aws-credentials@v1
      #with:
        #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
       # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #  aws-region: ${{ secrets.AWS_REGION }}

   # - name: Login to Amazon ECR
    #  id: login-ecr
     # uses: aws-actions/amazon-ecr-login@v1

    #- name: Build, tag, and push image to Amazon ECR
      #id: build-image
      #env:
        #ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        #ECR_REPOSITORY: new
       # working-directory: ./tags
      #run: |
        # Build a docker container and push it to ECR 
        #IMAGE_TAG=$( cat ./tags/tags.txt )
        #echo "$IMAGE_TAG"
        #varw=${{ steps.release.outputs.tag_name }}
        #echo "$varw"
        #docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$varw .
        #echo "Pushing image to ECR..."
        #docker push $ECR_REGISTRY/$ECR_REPOSITORY:$varw
        #echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$varw"